name: trading
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  chopper: ^7.2.0
  auto_route: ^8.0.3
  # Dependency Injection
  injectable: ^2.4.1
  get_it: ^7.6.4
  # Bloc for state management
  bloc: ^8.1.4

  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1


  kt_dart: ^1.1.0

  json_annotation: ^4.8.1

  uuid: ^4.3.3





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  chopper_generator: ^7.2.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  analyzer: ^6.4.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1





flutter:


  uses-material-design: true

  assets:
    - config/